dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.0

dotenv: .env
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
networks:
  development:
    verify: False
  mainnet-fork:
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    dai_eth_price_feed: '0x773616e4d11a78f511299002da57a0a94577f1f4'
    dai_token: '0x6B175474E89094C44Da98b954EedeAC495271d0F'
  mainnet:
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    dai_eth_price_feed: '0x773616e4d11a78f511299002da57a0a94577f1f4'
    dai_token: '0x6B175474E89094C44Da98b954EedeAC495271d0F'
  goerli:
    weth_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6'
    dai_usd_price_feed: '0x0d79df66BE487753B02D015Fb622DED7f0E9798d'
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    dai_token: '0xdc31ee1784292379fbb2964b3b9c4124d8f89c60'
    vrf_coordinator: '0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D'
    fau_token: '0xba62bcfcaafc6622853cca2be6ac7d845bc0f2dc'
    verify: True
  ganache-local: 
    verify: False
  ganache:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}