dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
dotenv: .env

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
wallets:
  from_key: ${PRIVATE_KEY}